config/routes.rb
Rails.application.routes.draw do
  

  get 'search_vakil/vakil_list'

  get 'search_vakil/search_by_city'

  get 'search_vakil/search_by_service'

  get 'search_vakil/search_by_city_and_service'
  get 'search_vakil/upload_data'
  post 'search_vakil/upload_city_data'
  post 'search_vakil/upload_service_data'
  post 'search_vakil/upload_data_to_database'
  resources :lawyer_services

  resources :lawyer_cities

   root 'search_vakil#index'

end

app/models/lawyer_city.rb
class LawyerCity < ActiveRecord::Base
end

app/models/lawyer_service.rb
class LawyerService < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_vakil_controller.rb
class SearchVakilController < ApplicationController
  require 'csv'
  def index
  end

  def vakil_list
    if !params[:search_by_city].blank?
        @lawyer_city = LawyerCity.find(params[:location])
        puts @lawyer_city.location
        @lawyercity = LawyerCity.where(:location =>@lawyer_city.location)
    elsif !params[:search_by_service].blank?
        @lawyer_service = LawyerService.find(params[:service])
        puts @lawyer_service.service_name
        @lawyerservice = LawyerService.where(:service_name =>@lawyer_service.service_name)
    elsif !params[:search_by_city_and_service].blank?
        @lawyer_cityr = LawyerCity.find(params[:location])
        @lawyercityr = LawyerCity.where(:location =>@lawyer_cityr.location)
        @lawyer_servicer = LawyerService.find(params[:service])
        @lawyerservicer = LawyerService.where(:service_name =>@lawyer_servicer.service_name)
        @lawyer_city_service = []
        @lawyerservicer.each do |service|
          @lawyercity = LawyerCity.where(:location =>@lawyer_cityr.location,:lawyer_code=>service.lawyer_code)
          if !@lawyercity.blank?
            @lawyer_city_service << service
          else
          end

        end
    end
  end

  def search_by_city
  end

  def search_by_service
  end

  def search_by_city_and_service
  end
  def upload_data

  end
  def upload_city_data
     CSV.foreach(params[:file_city].path, headers: true) do |row|
        @lawyer_city = LawyerCity.new
        @lawyer_city.lawyer_code = row[0]
        @lawyer_city.lawyer_namestring = row[1]
        @lawyer_city.location = row[3]
        @lawyer_city.exp = row[2]
        puts row[3]
        @lawyer_city.average_rating = row[4]
        @lawyer_city.save
    end
  end
    def upload_service_data
     CSV.foreach(params[:file_service].path, headers: true) do |row|
        @lawyer_service = LawyerService.new
        @lawyer_service.lawyer_code = row[0]
        @lawyer_service.service_code = row[1]
        @lawyer_service.service_name = row[2]
        @lawyer_service.service_charge = row[3]
        @lawyer_service.save
    end
  end
  def upload_data_to_database
    CSV.foreach('Lawyers_City_List.csv', :headers => true) do |row|
       @lawyer_city = LawyerCity.new
        @lawyer_city.lawyer_code = row[0]
        @lawyer_city.lawyer_namestring = row[1]
        @lawyer_city.location = row[3]
        @lawyer_city.exp = row[2]
        puts row[3]
        @lawyer_city.average_rating = row[4]
        @lawyer_city.save
        puts "I am saveed for city"

    end
    puts "Now i am started for service"
      CSV.foreach('Lawyer_Service_List.csv', :headers => true) do |row|
       @lawyer_service = LawyerService.new
        @lawyer_service.lawyer_code = row[0]
        @lawyer_service.service_code = row[1]
        @lawyer_service.service_name = row[2]
        @lawyer_service.service_charge = row[3]
        @lawyer_service.save
        puts "i am saved for service"
    end
    if @lawyer_service.save
      render :js => "alert('you have done ');"
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_vakil_helper.rb
module SearchVakilHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vakil Search</title>
 
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   
  </head>

  <body>
  <div class="row">

  <nav class="top-bar" data-topbar>
   <ul class="title-area"> 
    <li class="name"> 
        <h1><a href="/">Vakil Search</a></h1>
      </li>
     </ul> 
    
    </nav>
    </div>
    <div class="row">
      <p><%= flash[:notice] %></p>
      <p><%= flash[:error] %></p>
    </div>
    <%= yield %>

   
  </body>
</html>

app/views/search_vakil/_lawyer_by_city.html.erb
<div class="row">
	<div class="large-12 columns">
		<table>
		<thead>
			<tr>
			<th>
				Lawyer Name
			</th>
			<th>
				Lawyer Code

			</th>			
			<th>
				Lawyer Location(city)
			</th>			
			<th>
				Exp.
			</th>	
			<th>
				Average Rating
			</th>					
			</tr>
		</thead>
		<tbody>
		<%@lawyercity.each do |lawyer|%>
		<tr>
			<td>
				<%=lawyer.lawyer_namestring%>
			</td>
			<td>
				<%=lawyer.lawyer_code%>
			</td>	
			<td>
				<%=lawyer.location%>
			</td>	
			<td>
				<%=lawyer.exp%>
			</td>	

			<td>
				<%=lawyer.average_rating%>
			</td>												
		</tr>
		<%end%>

		</tbody>
		</table> 
	</div>

</div>

app/views/search_vakil/_lawyer_by_city_and_service.html.erb
<div class="row">
	<div class="large-12 columns">
		<table>
		<thead>
			<tr>
			<th>
				Lawyer Name
			</th>
			<th>
				Lawyer Code

			</th>			
			<th>
				Lawyer Location(city)
			</th>			
			<th>
				Service Code
			</th>		
			<th>
				Service Name
			</th>			
			<th>
				Service Charge
			</th>				
			<th>
				Exp.
			</th>	
			<th>
				Average Rating
			</th>					
			</tr>
		</thead>
		<tbody>
		<%@lawyer_city_service.each do |lawyer|%>
		<%@city = LawyerCity.where(:lawyer_code =>lawyer.lawyer_code)%>
		<tr>
			<td>
				<%=@city.first.lawyer_namestring%>
			</td>
			<td>
				<%=@city.first.lawyer_code%>
			</td>	
			<td>
				<%=@city.first.location%>
			</td>
			<td>
				<%=lawyer.service_code%>
			</td>
			<td>
				<%=lawyer.service_name%>
			</td>
			<td>
				<%=lawyer.service_charge%>
			</td>										
			<td>
				<%=@city.first.exp%>
			</td>	

			<td>
				<%=@city.first.average_rating%>
			</td>												
		</tr>
		<%end%>

		</tbody>
		</table> 
	</div>

</div>

app/views/search_vakil/_lawyer_by_service.html.erb
<div class="row">
	<div class="large-12 columns">
		<table>
		<thead>
			<tr>
			<th>
				Lawyer Name
			</th>
			<th>
				Lawyer Code

			</th>			
			<th>
				Lawyer Location(city)
			</th>			
			<th>
				Service Code
			</th>		
			<th>
				Service Name
			</th>			
			<th>
				Service Charge
			</th>				
			<th>
				Exp.
			</th>	
			<th>
				Average Rating
			</th>					
			</tr>
		</thead>
		<tbody>
		<%@lawyerservice.each do |lawyer|%>
		<%@city = LawyerCity.where(:lawyer_code =>lawyer.lawyer_code)%>
		<tr>
			<td>
				<%=@city.first.lawyer_namestring%>
			</td>
			<td>
				<%=@city.first.lawyer_code%>
			</td>	
			<td>
				<%=@city.first.location%>
			</td>
			<td>
				<%=lawyer.service_code%>
			</td>
			<td>
				<%=lawyer.service_name%>
			</td>
			<td>
				<%=lawyer.service_charge%>
			</td>										
			<td>
				<%=@city.first.exp%>
			</td>	

			<td>
				<%=@city.first.average_rating%>
			</td>												
		</tr>
		<%end%>

		</tbody>
		</table> 
	</div>

</div>

app/views/search_vakil/_not_found.html.erb
<div class="row">
	<div class="large-12 columns">
		<table>
		<thead>
			<tr>
			<th>
				Lawyer Name
			</th>
			<th>
				Lawyer Code

			</th>			
			<th>
				Lawyer Location(city)
			</th>			
			<th>
				Service Code
			</th>		
			<th>
				Service Name
			</th>			
			<th>
				Service Charge
			</th>				
			<th>
				Exp.
			</th>	
			<th>
				Average Rating
			</th>					
			</tr>
		</thead>
		<tbody>
		<tr>

		<td>
		    No record Found for this query
		</td>
		</tr>
		</tbody>
		</table> 
	</div>

</div>

app/views/search_vakil/index.html.erb
<div class="row">
<h2>
	Search Lawyer 
</h2>
</div>
<div class="row">
	<div class="large-12 columns">
		 <div class="large-4 columns">
		 	<%= link_to "Search by City(Loation)",search_vakil_search_by_city_path,:class=>"large-12 button success"%>
		 </div>
		 <div class="large-4 columns">
		 	<%= link_to "Search by Service",search_vakil_search_by_service_path,:class=>"large-12 button success"%>
		 </div>		 
		 <div class="large-4 columns">
		 	<%= link_to "Search by City and Service",search_vakil_search_by_city_and_service_path,:class=>"large-12 button success"%>
		 </div>		 
	</div>

</div>

app/views/search_vakil/search_by_city.html.erb
<div class="row">
<h2>
	Search Lawyer by City 
</h2>
</div>
<div class="row">
	<div class="large-12 columns">
		 <div class="large-12 columns">
		 	Select City (Location)
		 </div>
		 <div class="large-12 columns">
		 	<%= form_tag("/search_vakil/vakil_list", :method => "get") do %>
		 	  <div class="large-12 columns">
		 	   <%= hidden_field_tag "search_by_city",nil ,:value=>"search_by_city"%>
		 	   
			   <%= select_tag :location, options_from_collection_for_select(LawyerCity.all.group("location"), "id", "location"),:prompt => "Select City", :class=>"large-4 columns"%>
			  	</div>
			  	<div class="large-12 columns">
			    <%= submit_tag "Search lawyer",:class=>"button success large"%>
			  </div>
			<% end %>
		 </div>		 
	</div>

</div>

app/views/search_vakil/search_by_city_and_service.html.erb
<div class="row">
<h2>
	Search Lawyer by City and Service
</h2>
</div>
<div class="row">
	<div class="large-12 columns">
		 <div class="large-12 columns">
		 	Select City (Location)
		 </div>
		 <div class="large-12 columns">
		 	<%= form_tag("/search_vakil/vakil_list", :method => "get") do %>
		 	  <div class="large-12 columns">
		 	   <%= hidden_field_tag "search_by_city_and_service",nil ,:value=>"search_by_city_and_service"%>
		 	   
			   <%= select_tag :location, options_from_collection_for_select(LawyerCity.all.group("location"), "id", "location"),:prompt => "Select City", :class=>"large-4 columns"%>
			  	</div>
			  	<div>
			    <%= select_tag :service, options_from_collection_for_select(LawyerService.all.group("service_name"), "id", "service_name"),:prompt => "Select Service", :class=>"large-4 columns"%>
			  	</div>
			  	<div class="large-12 columns">
			    <%= submit_tag "Search lawyer",:class=>"button success large"%>
			  </div>
			<% end %>
		 </div>		 
	</div>

</div>

app/views/search_vakil/search_by_service.html.erb
<div class="row">
<h2>
	Search Lawyer by Service
</h2>
</div>
<div class="row">
	<div class="large-12 columns">
		 <div class="large-12 columns">
		 	Select City (Location)
		 </div>
		 <div class="large-12 columns">
		 	<%= form_tag("/search_vakil/vakil_list", :method => "get") do %>
		 	  <div class="large-12 columns">
		 	   <%= hidden_field_tag "search_by_service",nil ,:value=>"search_by_service"%>
		 	   
			   <%= select_tag :service, options_from_collection_for_select(LawyerService.all.group("service_name"), "id", "service_name"),:prompt => "Select Service", :class=>"large-4 columns"%>
			  	</div>
			  	<div class="large-12 columns">
			    <%= submit_tag "Search Lawyer",:class=>"button success large"%>
			  </div>
			<% end %>
		 </div>		 
	</div>

</div>

app/views/search_vakil/upload_data.html.erb
<div class="row">
	<div class="large-12 columns">
		<div class="large.5 columns">
			<h3>
				Upload Lawyer city Data

			</h3>
			<%=link_to "upload data" ,search_vakil_upload_data_to_database_path ,:method=>:post,:class=>"button success"%>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<%= form_tag search_vakil_upload_city_data_path, multipart: true do%>
			<%= file_field_tag :file_city%>
			<%= submit_tag "Import Data ",:class=>"button success"%>
		<%end%>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<div class="large.5 columns">
			<h3>
				Upload Lawyer service Data
			</h3>
		</div>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<%= form_tag search_vakil_upload_service_data_path, multipart: true do%>
			<%= file_field_tag :file_service%>
			<%= submit_tag "Import Data ",:class=>"button success"%>
		<%end%>
	</div>
</div>

app/views/search_vakil/vakil_list.html.erb
<div class="row">
<h2>
	Lawyer List: -  
</h2>
</div>
<%if !@lawyercity.blank?%>
	<%= render "lawyer_by_city" %>
<%elsif !@lawyerservice.blank? %>
	<%= render "lawyer_by_service" %>
<%elsif !@lawyer_city_service.blank?%>
	<%= render "lawyer_by_city_and_service" %>
<%else%>
 <%= render "not_found" %>
<%end%>